# Generated by Django 2.2.5 on 2021-06-29 14:20

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0003_rfi_tsox_borrado'),
    ]

    operations = [
        migrations.CreateModel(
            name='fondo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_fondo', models.TextField(blank=True, null=True)),
                ('duracion_fondo', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, null=True, size=None)),
                ('sector_fondo', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, null=True, size=None)),
                ('ytm_fondo', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, null=True, size=None)),
                ('risk_fondo', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, null=True, size=None)),
                ('cntry_of_risk_fondo', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, null=True, size=None)),
                ('trader_fondo', models.TextField(blank=True, null=True)),
                ('tamano_fondo', models.BigIntegerField(blank=True, null=True)),
                ('notas_fondo', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
