# Generated by Django 2.2.5 on 2021-07-02 15:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BASES', '0010_auto_20210702_1433'),
        ('ordenes', '0004_fondo'),
    ]

    operations = [
        migrations.AddField(
            model_name='fondo',
            name='ejecutivo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='BASES.ejecutivos'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fondo',
            name='tamano_fondo',
            field=models.BigIntegerField(blank=True, default=0, null=True),
        ),
    ]
