# Generated by Django 2.2.5 on 2021-07-05 16:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0005_auto_20210702_1524'),
    ]

    operations = [
        migrations.CreateModel(
            name='fondo_salida',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_asignado', models.TextField(blank=True, null=True)),
                ('notas_asignado', models.TextField(blank=True, null=True)),
                ('fondo_asignado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ordenes.fondo')),
                ('orden_asignada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ordenes.rfi_tsox')),
            ],
        ),
    ]
