# Generated by Django 2.2.5 on 2021-08-10 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0006_fondo_salida'),
    ]

    operations = [
        migrations.CreateModel(
            name='carteras_bbg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fondo', models.TextField(blank=True, null=True)),
                ('sector', models.TextField(blank=True, null=True)),
                ('nemo', models.TextField(blank=True, null=True)),
                ('weight', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True)),
                ('mkt_val', models.BigIntegerField(blank=True, null=True)),
                ('pos_val', models.BigIntegerField(blank=True, null=True)),
                ('px_close', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True)),
                ('crncy', models.TextField(blank=True, null=True)),
                ('isin', models.TextField(blank=True, null=True)),
                ('ejecutivo', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
