# Generated by Django 2.2.5 on 2021-08-26 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0008_holders_salida_intenciones_pasadas_salida'),
    ]

    operations = [
        migrations.AddField(
            model_name='fondo',
            name='pais_fondo',
            field=models.TextField(blank=True, null=True),
        ),
    ]
