# Generated by Django 3.2.6 on 2021-09-13 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0009_fondo_pais_fondo'),
    ]

    operations = [
        migrations.AddField(
            model_name='fondo',
            name='email_fondo',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fondo',
            name='ticker_fondo',
            field=models.TextField(blank=True, null=True),
        ),
    ]
