# Generated by Django 2.2.5 on 2020-06-01 19:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('BASES', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='clientes_rfl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='hd_aux',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(null=True)),
                ('cliente', models.TextField()),
                ('monto', models.BigIntegerField(default=0, null=True)),
                ('operador', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='lva',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nemo', models.TextField()),
                ('tipo', models.TextField()),
                ('unidad_reaj', models.CharField(max_length=3)),
                ('precio', models.DecimalField(decimal_places=5, max_digits=8)),
                ('plazo_economico', models.IntegerField()),
                ('tir_val', models.DecimalField(decimal_places=4, max_digits=6)),
                ('tir_transa', models.DecimalField(decimal_places=3, max_digits=4)),
                ('categoria', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='operador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operador', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='posiciones',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fuente_del_instrumento', models.TextField(choices=[('AFP', 'AFP'), ('FFMM', 'FFMM'), ('FIP', 'FIP'), ('FNR', 'FNR'), ('FYNSA', 'FYNSA'), ('SEG_G', 'SEG_G'), ('SEG_V', 'SEG_V')])),
                ('institucion', models.TextField()),
                ('nemotecnico', models.TextField()),
                ('valor_nominal', models.BigIntegerField()),
                ('marca', models.DecimalField(decimal_places=2, max_digits=4)),
                ('dur_rskam', models.DecimalField(decimal_places=3, max_digits=5)),
                ('maturity', models.DateField()),
                ('tipo_instrumento', models.TextField()),
                ('crncy', models.TextField()),
                ('fecha_subida', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='risk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nemo', models.TextField()),
                ('tipo', models.TextField()),
                ('riesgo', models.TextField()),
                ('duracion', models.DecimalField(decimal_places=8, max_digits=10)),
                ('tir', models.DecimalField(decimal_places=2, max_digits=4)),
            ],
        ),
        migrations.CreateModel(
            name='hd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(null=True)),
                ('monto', models.BigIntegerField(default=0, null=True)),
                ('cliente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='BASES.clientes')),
                ('operador', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='BASES.operador')),
            ],
        ),
    ]
