# Generated by Django 2.2.5 on 2021-01-04 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RFL', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='tr',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instrumento', models.TextField()),
                ('tipo', models.TextField()),
                ('cantidad', models.IntegerField()),
                ('reajuste', models.TextField()),
                ('tir_media', models.DecimalField(decimal_places=2, max_digits=5)),
                ('duracion', models.DecimalField(decimal_places=2, max_digits=5)),
                ('rating', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='risk',
            name='moneda',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='risk',
            name='monto_outstanding',
            field=models.BigIntegerField(default='0'),
        ),
        migrations.AlterField(
            model_name='risk',
            name='duracion',
            field=models.DecimalField(decimal_places=8, default='0', max_digits=10),
        ),
        migrations.AlterField(
            model_name='risk',
            name='nemo',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='risk',
            name='riesgo',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='risk',
            name='tipo',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='risk',
            name='tir',
            field=models.DecimalField(decimal_places=2, default='0', max_digits=4),
        ),
    ]
