# Generated by Django 2.2.5 on 2021-01-04 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RFL', '0002_auto_20210104_1355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='risk',
            name='duracion',
            field=models.DecimalField(decimal_places=8, max_digits=10),
        ),
        migrations.AlterField(
            model_name='risk',
            name='tir',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
    ]
