# Generated by Django 2.2.5 on 2021-01-04 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RFL', '0004_auto_20210104_1359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='risk',
            name='moneda',
            field=models.TextField(default='-'),
        ),
    ]
