# Generated by Django 2.2.5 on 2021-01-04 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RFL', '0005_auto_20210104_1359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='risk',
            name='duracion',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='risk',
            name='moneda',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='risk',
            name='monto_outstanding',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='risk',
            name='tir',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
