# Generated by Django 2.2.5 on 2021-01-04 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RFL', '0006_auto_20210104_1405'),
    ]

    operations = [
        migrations.CreateModel(
            name='archivos_cintas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tr', models.FileField(upload_to='')),
                ('rsk', models.FileField(upload_to='')),
            ],
        ),
    ]
