# Generated by Django 2.2.5 on 2021-01-08 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RFL', '0009_auto_20210108_1335'),
    ]

    operations = [
        migrations.CreateModel(
            name='bonos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instrumento', models.TextField()),
                ('rating', models.TextField()),
            ],
        ),
    ]
