# Generated by Django 2.2.5 on 2021-01-14 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RFL', '0010_bonos'),
    ]

    operations = [
        migrations.AddField(
            model_name='bonos',
            name='tipo',
            field=models.TextField(default=''),
        ),
    ]
