# Generated by Django 2.2.5 on 2021-02-04 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RFL', '0012_actividada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posiciones',
            name='fecha_subida',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='posiciones',
            name='fuente_del_instrumento',
            field=models.TextField(),
        ),
    ]
