# Generated by Django 2.2.5 on 2021-02-05 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RFL', '0015_posiciones_fecha_subida'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posiciones',
            name='crncy',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='posiciones',
            name='dur_rskam',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='posiciones',
            name='fecha_subida',
            field=models.DateField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='posiciones',
            name='fuente_del_instrumento',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='posiciones',
            name='institucion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='posiciones',
            name='marca',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='posiciones',
            name='maturity',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='posiciones',
            name='nemotecnico',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='posiciones',
            name='tipo_instrumento',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='posiciones',
            name='valor_nominal',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
