# Generated by Django 2.2.5 on 2021-02-22 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RFL', '0017_auto_20210205_1354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lva',
            name='tir_transa',
            field=models.DecimalField(decimal_places=3, max_digits=6),
        ),
        migrations.AlterField(
            model_name='lva',
            name='tir_val',
            field=models.DecimalField(decimal_places=4, max_digits=7),
        ),
    ]
