# Generated by Django 2.2.5 on 2021-03-05 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RFL', '0019_lva_vector'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lva_vector',
            name='fecha',
            field=models.DateField(blank=True, null=True),
        ),
    ]
