# Generated by Django 2.2.5 on 2021-03-05 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RFL', '0020_auto_20210305_1423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bonos',
            name='tipo',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
