# Generated by Django 2.2.5 on 2021-03-08 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RFL', '0022_supercintas'),
    ]

    operations = [
        migrations.AddField(
            model_name='bonos',
            name='reaj',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='supercintas',
            name='reaj',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
