# Generated by Django 2.2.5 on 2020-06-01 19:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='bases',
            fields=[
                ('linea', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('fynsa', models.TextField(choices=[('NO', 'NO'), ('SI', 'SI')], null=True)),
                ('otc_tr', models.TextField(choices=[('OTC', 'OTC'), ('TR', 'TR')])),
                ('nemo', models.TextField()),
                ('dias', models.IntegerField(default=0, null=True)),
                ('monto', models.BigIntegerField(default=0, null=True)),
                ('tipo_de_pago', models.TextField(choices=[('PM', 'PM'), ('PH', 'PH')])),
                ('buy', models.TextField()),
                ('seller', models.TextField()),
                ('trader_buy', models.TextField(default=0, null=True)),
                ('trader_seller', models.TextField(default=0, null=True)),
                ('tasa', models.DecimalField(decimal_places=2, max_digits=4, null=True)),
                ('valor_final', models.BigIntegerField(default=0, null=True)),
                ('fee_buyer', models.IntegerField(default=0, null=True)),
                ('fee_seller', models.IntegerField(default=0, null=True)),
                ('fee_buyer_moneda', models.TextField(choices=[('CLP', 'CLP'), ('USD', 'USD')], null=True)),
                ('fee_seller_moneda', models.TextField(choices=[('CLP', 'CLP'), ('USD', 'USD')], null=True)),
                ('compra_depo', models.BigIntegerField(default=0, null=True)),
                ('venta_depo', models.BigIntegerField(default=0, null=True)),
                ('util_depo', models.BigIntegerField(default=0, null=True)),
                ('valor_clp', models.BigIntegerField(default=0, null=True)),
                ('fee_buyer_clp', models.IntegerField(default=0, null=True)),
                ('fee_seller_clp', models.IntegerField(default=0, null=True)),
                ('participante_1', models.TextField(null=True)),
                ('participante_2', models.TextField(null=True)),
                ('tipo_de_cambio', models.DecimalField(decimal_places=2, default=0, max_digits=5, null=True)),
                ('uf', models.DecimalField(decimal_places=2, default=0, max_digits=7, null=True)),
                ('concate', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='facturas_bases',
            fields=[
                ('linea', models.AutoField(primary_key=True, serialize=False)),
                ('folio_factura', models.IntegerField(default=0, null=True, unique=True)),
                ('cliente', models.TextField(default=0, null=True)),
                ('fecha_emision', models.DateField()),
                ('monto_neto', models.BigIntegerField(default=0, null=True)),
                ('monto_total', models.BigIntegerField(default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='operador',
            fields=[
                ('nombre_operador', models.TextField(primary_key=True, serialize=False)),
                ('abreviatura', models.CharField(max_length=4)),
                ('mesa', models.TextField(choices=[('RFL', 'Local'), ('RFI', 'Internacional'), ('BASES', 'Bases')])),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='serie_generacion_total_diaria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('cliente', models.TextField()),
                ('total_consolidada', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='clientes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField(default='', null=True)),
                ('nacionalidad_cliente', models.TextField(null=True)),
                ('categoria', models.TextField(null=True)),
                ('operador_contraparte', models.TextField(null=True)),
                ('esta_activo', models.BooleanField(default=True, null=True)),
                ('email', models.TextField(null=True)),
                ('email_cco', models.TextField(null=True)),
                ('factura', models.BooleanField(default=False)),
                ('cliente_principal', models.TextField(default='', null=True)),
                ('anidado', models.BooleanField(default=False)),
                ('operador_fynsa', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='BASES.operador')),
            ],
        ),
    ]
