# Generated by Django 2.2.5 on 2020-06-02 21:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BASES', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes',
            name='anidado',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='categoria',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='cliente_principal',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='email',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='email_cco',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='esta_activo',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='factura',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='nacionalidad_cliente',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='operador_contraparte',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='operador_fynsa',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='BASES.operador'),
        ),
    ]
