# Generated by Django 2.2.5 on 2020-06-22 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BASES', '0002_auto_20200602_2149'),
    ]

    operations = [
        migrations.CreateModel(
            name='serie_generacion_mensual',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('monto_bases', models.BigIntegerField()),
                ('monto_depositos', models.BigIntegerField()),
                ('monto_total', models.BigIntegerField()),
                ('monto_meta', models.BigIntegerField()),
                ('clientes_80', models.IntegerField()),
                ('clientes_activos', models.IntegerField()),
            ],
        ),
    ]
