# Generated by Django 2.2.5 on 2020-11-03 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BASES', '0004_auto_20200622_1706'),
    ]

    operations = [
        migrations.CreateModel(
            name='serie_montos_mensual_por_cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(blank=True, null=True)),
                ('cliente', models.TextField(default='', null=True)),
                ('monto_bases_otc', models.BigIntegerField(blank=True, null=True)),
                ('monto_bases_tr', models.BigIntegerField(blank=True, null=True)),
                ('monto_depos_otc', models.BigIntegerField(blank=True, null=True)),
                ('monto_depos_tr', models.BigIntegerField(blank=True, null=True)),
                ('monto_total', models.BigIntegerField(blank=True, null=True)),
            ],
        ),
    ]
