# Generated by Django 2.2.5 on 2020-11-11 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BASES', '0005_serie_montos_mensual_por_cliente'),
    ]

    operations = [
        migrations.CreateModel(
            name='serie_generacion_mensual_por_cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(blank=True, null=True)),
                ('cliente', models.TextField(default='', null=True)),
                ('gen_depo', models.BigIntegerField(blank=True, null=True)),
                ('gen_bases', models.BigIntegerField(blank=True, null=True)),
                ('prov_bases', models.BigIntegerField(blank=True, null=True)),
                ('prov_depos', models.BigIntegerField(blank=True, null=True)),
            ],
        ),
    ]
