# Generated by Django 2.2.5 on 2020-12-14 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BASES', '0006_serie_generacion_mensual_por_cliente'),
    ]

    operations = [
        migrations.CreateModel(
            name='cliente_trader',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institucion_trader', models.TextField(null=True)),
            ],
        ),
        migrations.AddField(
            model_name='bases',
            name='institucion_trader_buyer',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='bases',
            name='institucion_trader_participante_1',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='bases',
            name='institucion_trader_participante_2',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='bases',
            name='institucion_trader_seller',
            field=models.TextField(null=True),
        ),
    ]
