# Generated by Django 2.2.5 on 2021-05-10 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BASES', '0008_auto_20210317_1413'),
    ]

    operations = [
        migrations.AddField(
            model_name='bases',
            name='tasa_buyer',
            field=models.DecimalField(decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='bases',
            name='tasa_seller',
            field=models.DecimalField(decimal_places=2, max_digits=4, null=True),
        ),
    ]
