# Generated by Django 2.2.5 on 2021-07-02 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BASES', '0009_auto_20210510_2100'),
    ]

    operations = [
        migrations.CreateModel(
            name='ejecutivos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ejecutivo', models.TextField(blank=True, null=True)),
                ('mesa', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='bases',
            name='tipo_de_pago',
            field=models.TextField(blank=True, choices=[('PM', 'PM'), ('PH', 'PH'), ('CN', 'CN')], null=True),
        ),
    ]
