# Generated by Django 2.2.5 on 2020-09-22 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='bonos_rfi',
            fields=[
                ('cusip', models.TextField(primary_key=True, serialize=False)),
                ('duration', models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=5, null=True)),
                ('papel', models.TextField(blank=True, null=True)),
                ('industry_sector', models.TextField(blank=True, default='-', null=True)),
                ('industry_group', models.TextField(blank=True, default='-', null=True)),
                ('cntry_of_risk', models.CharField(blank=True, default='-', max_length=2, null=True)),
                ('industria', models.TextField(blank=True, default='-', null=True)),
                ('risk', models.TextField(blank=True, default='', null=True)),
                ('tasa', models.IntegerField(blank=True, default='', null=True)),
                ('fecha_subida', models.DateField(blank=True, null=True)),
                ('maturity', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='clientes_rfi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fondo', models.TextField(blank=True, null=True)),
                ('nombre_cliente', models.TextField(blank=True, null=True, unique=True)),
                ('categoria', models.TextField(blank=True, null=True)),
                ('pais', models.CharField(blank=True, max_length=3, null=True)),
                ('operador_fynsa', models.TextField(blank=True, null=True)),
                ('activo', models.BooleanField(blank=True, default=True, null=True)),
                ('prospecto', models.BooleanField(blank=True, default=False, null=True)),
                ('trader_contraparte', models.TextField(blank=True, null=True)),
                ('final', models.BooleanField(blank=True, default='t', null=True)),
                ('categoria_fynsa', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='rfi_beta',
            fields=[
                ('linea', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('ejecutivo', models.CharField(max_length=7, null=True)),
                ('papel', models.TextField()),
                ('cusip', models.TextField(null=True)),
                ('operacion', models.TextField(choices=[('venta', 'venta'), ('compra', 'compra')])),
                ('nominales', models.IntegerField()),
                ('mesa', models.DecimalField(decimal_places=3, max_digits=7, null=True)),
                ('ejecutivo_precio', models.DecimalField(decimal_places=2, default=0, max_digits=7, null=True)),
                ('cliente_precio', models.DecimalField(decimal_places=2, default=0, max_digits=7, null=True)),
                ('ingreso_ejecutivo', models.DecimalField(decimal_places=2, max_digits=8, null=True)),
                ('ingreso_mesa', models.DecimalField(decimal_places=2, max_digits=9, null=True)),
                ('contraparte', models.TextField()),
                ('spread_mesa', models.DecimalField(decimal_places=3, max_digits=5, null=True)),
                ('comprador', models.TextField()),
                ('vendedor', models.TextField()),
                ('country_of_risk', models.CharField(max_length=5, null=True)),
                ('crncy', models.CharField(max_length=5, null=True)),
                ('duration', models.DecimalField(blank=True, decimal_places=3, default=0.0, max_digits=5, null=True)),
                ('tipo_de_cambio', models.DecimalField(decimal_places=2, max_digits=6, null=True)),
                ('fecha_subido', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
    ]
