# Generated by Django 2.2.5 on 2020-10-05 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RFI', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='rfi_generacion_historica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(blank=True, null=True)),
                ('pais', models.CharField(blank=True, max_length=3, null=True)),
                ('categoria', models.TextField(blank=True, null=True)),
                ('nombre_cliente', models.TextField(blank=True, null=True, unique=True)),
                ('generacion', models.IntegerField(blank=True, null=True)),
                ('spread', models.DecimalField(decimal_places=3, max_digits=5, null=True)),
            ],
        ),
    ]
