# Generated by Django 2.2.5 on 2020-10-05 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RFI', '0002_rfi_generacion_historica'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rfi_generacion_historica',
            name='nombre_cliente',
            field=models.TextField(blank=True, null=True),
        ),
    ]
