# Generated by Django 2.2.5 on 2020-10-23 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RFI', '0003_auto_20201005_2016'),
    ]

    operations = [
        migrations.CreateModel(
            name='rfi_generacion_comite_temporal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pais', models.CharField(blank=True, max_length=3, null=True)),
                ('categoria', models.TextField(blank=True, null=True)),
                ('nombre_cliente', models.TextField(blank=True, null=True)),
                ('generacion_brk', models.IntegerField(blank=True, null=True)),
                ('generacion_finales', models.IntegerField(blank=True, null=True)),
                ('generacion_bancos_brk', models.IntegerField(blank=True, null=True)),
                ('generacion_total', models.IntegerField(blank=True, null=True)),
                ('spread_brk', models.IntegerField(blank=True, null=True)),
                ('spread_finales', models.IntegerField(blank=True, null=True)),
                ('spread_banco_brk', models.IntegerField(blank=True, null=True)),
                ('generacion_brk_t_1', models.IntegerField(blank=True, null=True)),
                ('generacion_finales_t_1', models.IntegerField(blank=True, null=True)),
                ('generacion_bancos_brk_t_1', models.IntegerField(blank=True, null=True)),
                ('generacion_total_t_1', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
