# Generated by Django 2.2.5 on 2020-10-23 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RFI', '0004_rfi_generacion_comite_temporal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rfi_generacion_comite_temporal',
            name='spread_banco_brk',
            field=models.DecimalField(decimal_places=3, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='rfi_generacion_comite_temporal',
            name='spread_brk',
            field=models.DecimalField(decimal_places=3, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='rfi_generacion_comite_temporal',
            name='spread_finales',
            field=models.DecimalField(decimal_places=3, max_digits=5, null=True),
        ),
    ]
