# Generated by Django 2.2.5 on 2021-05-31 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RFI', '0005_auto_20201023_1853'),
    ]

    operations = [
        migrations.DeleteModel(
            name='bonos_rfi',
        ),
    ]
