# Generated by Django 2.2.5 on 2021-05-31 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RFI', '0006_delete_bonos_rfi'),
    ]

    operations = [
        migrations.CreateModel(
            name='rfi_bonos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cusip', models.TextField(blank=True, null=True)),
                ('security_name', models.TextField(blank=True, null=True)),
                ('short_name', models.TextField(blank=True, null=True)),
                ('bb_composite', models.CharField(blank=True, default='NR', max_length=4, null=True)),
                ('payment_rank', models.CharField(blank=True, max_length=40, null=True)),
                ('cntry_of_risk', models.CharField(blank=True, max_length=2, null=True)),
                ('yas_mod_dur', models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=7, null=True)),
                ('yas_bond_yld', models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=7, null=True)),
                ('classification', models.TextField(blank=True, default='-', null=True)),
                ('industria', models.TextField(blank=True, null=True)),
                ('ising', models.TextField(blank=True, null=True)),
                ('risk', models.TextField(blank=True, default='NR', null=True)),
                ('dur_text', models.TextField(blank=True, null=True)),
                ('tasa', models.IntegerField(blank=True, default='', null=True)),
                ('fecha_subida', models.DateField(blank=True, null=True)),
                ('maturity', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
