# Generated by Django 2.2.5 on 2021-06-04 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RFI', '0008_pruebaarraymodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='rfi_bonos',
            name='yas_bond_porcentaje',
            field=models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=9, null=True),
        ),
    ]
