# Generated by Django 2.2.5 on 2021-07-28 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RFI', '0010_rfi_bonos_yas_bond_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='rfi_beta',
            name='cliente',
            field=models.TextField(blank=True, null=True),
        ),
    ]
